name: CI
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      # Get Date for Cache Key
      - name: Get Date
        id: get-date
        run: |
          echo "::set-output name=date::$(/bin/date -u "+%Y%m%d")"
        shell: bash

      # Cache Buildozer global directory
      - name: Cache Buildozer global directory
        uses: actions/cache@v3
        with:
          path: .buildozer_global
          key: buildozer-global-${{ hashFiles('buildozer.spec') }}

      # Cache the .buildozer directory
      - uses: actions/cache@v3
        with:
          path: .buildozer
          key: ${{ runner.os }}-${{ steps.get-date.outputs.date }}-${{ hashFiles('buildozer.spec') }}

      # Manually pull the image and build with Buildozer
      - name: Pull Buildozer Docker Image and Build
        run: |
          docker pull kivy/buildozer:1.0.0  # Specify the image version (replace '1.0.0' if needed)
          docker run --rm -v $(pwd):/project kivy/buildozer:1.0.0 buildozer android debug
        env:
          HOME: /tmp  # Workaround for certain environments like GitHub Actions to handle file permissions correctly

      # Upload the artifacts (APK or others)
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: ./bin/*  # Path to your resulting APK or other artifacts
